language: python
install:
- pip install markdown
- pip install pelican
- pip install ghp-import
script:
- make github
- git remote remove origin
- git remote add origin https://$GH_TOKEN@github.com/techemstudios/blog
- git push -f origin gh-pages
env:
  global:
  - secure: d82/WeDwiHBT8DQrWEu7/gOShH0IzBkRdzHJ9MipAYA7bgea0M7FP56iheWGriQUqpPfOGeVQcriadg05QDMbLqfJR6uLLSKbXwmPv9AqFQqaEX9WS2v3IVj8qvmHbcysrcRhkfjVgdwuo/Ltksdg1YjOj3qXVNz1FDxJHXFM2hagbQjElgZSG0vgOXCLX6yZsVNwg5gxd7SYpkEKwW4V0QU0DBP0N98Btqu/xeNNJgLeTja5Rk3zbXxV2vDJkZydPbtLVI07FNeM+nU9xNPx/9jLk/7XEvQ/vXadipW0ZuAnwBNIm2D31KSiWGHxLWTLdB6oUx6S6AwS3GhtLRS+QJB/vgzE7K+azrgQ7xrBQ/2BAz6n2Mru07DkdVYheak3vBkYaazkWqRtVw+4eErpCARRt+eVlik45iv3CbOjxZEgcPPyyFrU3Y6ggd7QmRUOcrnf93ez8zz1xqPcRLhobuoqucCt/I/Ep0pDRG4xU10krtNptGbEXWKaDMg/mvmeTSMhav6icdVDoS3nltAvqhY8IChe9SSr3RWBq6y0qlopyHqq5ZMgmPka4+SfoznFy9zvxI4JVD/nbh6uqg/VIFZo1z6FKlXR/vjtcnit0k+d3vBmMw2vyPHvMLJ3MTT3/ge+HZEw1GyDbkNrXMc3le+jL+LGWDFpyw8y/wmKMw=
notifications:
  slack:
    secure: cYNKMbvodUUJ9Mcb58N+vr4NnKVsXmhfJtlztXdMaBkP05il5Ux/E2jhLBG7clVWy2VahLIXDIbyc9r1a4fynSn8ay0pcrnQtjjiVlqZnPQXaYw8X6nrxM154D1FWdGo+7wCVTlCu+1QPJYRDX/kapYre2iubPW8mK4JUVgDNQjmZ4/4icpkhqTH+zYv/NCCznbeHuNJZRWoUaUycd6R7p7D3Q6I3h96CYL6l8l6bP2gxcZiyAOipOq1gFBBVzK/ochJLhUjjy1MMReGuVin1oXCOWIT7OltfaNDet4We+6ma6018Ar9d9tRtIfadPY9YrV0coDKX86dchTBvpazsTlHsy+WWs7N9Gzy64XNqnjLwqWd35KFdfHniV1TNFLBVhmfXI3wi6YzEx2+Sz6L2na1S8GQNESbGEeVrAlp1IDJM6DTCUjU80jKa9MQvxb4MQdEmDzjFNiXExsFcP5nGxnXYf+YqtAa9DwJFUelBc2hlrmnrrqHusCDW3Y3taVwgoSpCMV7B8obfFX28GXRLLwnNB722qqRJeK5oH+sbe0DzmJbKBGMWFvwVmKQ9azHO8VgqImAbcRCxk2meul+iXBYaPjIHhFQcBos2maJmO06b3psowJZHFI2vDxJ6wMa/W4nIUVkiooO3vTK6T4O5PxPmCNYWzTCyaK7hJxfIck=
