language: python
install:
- pip install markdown
- pip install pelican
- pip install ghp-import
script:
- make github
- git remote remove origin
- git remote add origin https://$GH_TOKEN@github.com/techemstudios/blog
- git push -f origin gh-pages
env:
  global:
    secure: GXxjGYV7SyY/Snw4ZchLgwmYGCRfnbcN8ZOKAvk/VKBOmbU6jEYbNx+zflNgyQlDj1+YwoFQXNEarqO3FWUfddaBvI2KA+GpD0cOnyEIEPDk2ma8qIUUiMNZEfULzQjvbtUpowzc7Hohp7oyikbjjL49KYlYrRx/u5CsudQ7hSrVQ1b43P/y+rJDMzigNNLQotIBc0TOLtp6ScwaOa2r7j0AyQn6fckdT69geEZWt+UfwkQa7ixQAc8qX1nuAHbDvDpauFZkFzRQmqKez9A4sajujddXjJydgosGuBgaJjc/XQaAJzcaVvyFix9VD/XBROQIGouZGzMM1jahahGViWRe66W+EF0UBWBMQhVaF1hLmYhj9ymDBayEy69UXQ+pems9UxgSypixWbC2FFNn31K5nQB/U8HlegXHWtsHxV2QBDKHtVRgzGPGGEzVwOdy5c9rB54TZBdRI/TLB9Ty3LTdBEq0r6rj4UGT/+SzmyxzeNfB0H4vmJPIGKbz7zmNUMWujjYtVUJIbI/Ld5qQQNx2YsUAokm4vW2B0xQEyc4RkgIw5sp/vsbAFnm2WlceVjrYiji3B4cJkSIIlocTh433R+ziFxaTcf6KoW5oODqY/FknJo1ejdaS1ooK09iidwcLUoSOLD3xCKu1tgeDucGpBHgB+uKBFJJa35vKmu0=
notifications:
  slack:
    secure: cYNKMbvodUUJ9Mcb58N+vr4NnKVsXmhfJtlztXdMaBkP05il5Ux/E2jhLBG7clVWy2VahLIXDIbyc9r1a4fynSn8ay0pcrnQtjjiVlqZnPQXaYw8X6nrxM154D1FWdGo+7wCVTlCu+1QPJYRDX/kapYre2iubPW8mK4JUVgDNQjmZ4/4icpkhqTH+zYv/NCCznbeHuNJZRWoUaUycd6R7p7D3Q6I3h96CYL6l8l6bP2gxcZiyAOipOq1gFBBVzK/ochJLhUjjy1MMReGuVin1oXCOWIT7OltfaNDet4We+6ma6018Ar9d9tRtIfadPY9YrV0coDKX86dchTBvpazsTlHsy+WWs7N9Gzy64XNqnjLwqWd35KFdfHniV1TNFLBVhmfXI3wi6YzEx2+Sz6L2na1S8GQNESbGEeVrAlp1IDJM6DTCUjU80jKa9MQvxb4MQdEmDzjFNiXExsFcP5nGxnXYf+YqtAa9DwJFUelBc2hlrmnrrqHusCDW3Y3taVwgoSpCMV7B8obfFX28GXRLLwnNB722qqRJeK5oH+sbe0DzmJbKBGMWFvwVmKQ9azHO8VgqImAbcRCxk2meul+iXBYaPjIHhFQcBos2maJmO06b3psowJZHFI2vDxJ6wMa/W4nIUVkiooO3vTK6T4O5PxPmCNYWzTCyaK7hJxfIck=
